column_width = 120
syntax = "Luau"
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 3
quote_style = "AutoPreferDouble"
call_parentheses = "Input"
collapse_simple_statement = "ConditionalOnly"
space_after_function_names = "Never"

[sort_requires]
enabled = true
